image: docker

services:
  - docker:dind

stages:
  - test-backend
  - deploy

test-backend:
  stage: test-backend
  image: golang:latest
  only:
    - develop
    - production
  before_script:
    - cd /builds/frknkara/todo/server
    - go mod download
  script:
    - go test ./...

test-frontend:
  stage: test-frontend
  image: node:latest
  only:
    - develop
    - production
  before_script:
    - cd /builds/frknkara/todo/client
    - npm install
  script:
    - npm run test --no-watch

step-deploy-prod:
  stage: deploy
  only:
    - production
  script:
    - sudo apt-get install -y python3-pip
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install docker-compose
    - sudo docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
  environment: production
  when: manual
