image: docker

services:
  - docker:dind

stages:
  - test-backend
  - deploy

test-backend:
  stage: test-backend
  image: golang:latest
  only:
    - develop
    - production
  before_script:
    - cd /builds/frknkara/todo/server
    - go mod download
  script:
    - go get gotest.tools/gotestsum
    - gotestsum ./... --junitfile report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: report.xml

step-deploy-prod:
  stage: deploy
  only:
    - production
  script:
    - sudo apt-get install -y python3-pip
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install docker-compose
    - sudo docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
  environment: production
  when: manual
