image: docker

services:
  - docker:dind

stages:
  - test-backend
  - deploy

test-backend:
  stage: test-backend
  image: golang:1.17-alpine
  only:
    - develop
    - production
  before_script:
    - mkdir -p $GOPATH/src/gitlab.com/frknkara/todo
    - cd $GOPATH/src/gitlab.com/frknkara/todo/server
    - go mod download
  script:
    - go test ./...

step-deploy-prod:
  stage: deploy
  only:
    - production
  script:
    - sudo apt-get install -y python3-pip
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install docker-compose
    - sudo docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
  environment: production
  when: manual
